version: "3.4"

services:
  server:
    image: caddy:alpine
    depends_on:
      - backend
    volumes:
      - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.blog.rule: Host(`snowtricks.anagraph.org`)
      traefik.http.routers.blog.entrypoints: web
    networks:
      - proxy
      - snowtricks

  backend:
    build:
      context: .
      dockerfile: system/backend/Dockerfile
    volumes:
      - .:/app
      - ./system/backend/php-custom.ini:/usr/local/etc/php/php.ini
    networks:
      - snowtricks

volumes:
  caddy_data:
  caddy_config:

networks:
  snowtricks:
  proxy:
    external: true