version: "3.5"

services:
  frontend:
    image: node:12-alpine
    depends_on:
      - server
    volumes:
      - ./:/app
    working_dir: /app
#    Command below is for dev, you can restart it with 'docker-compose restart frontend'
    command: "npm run watch"
#    Command below is for production
#    command: "npm run build"

  server:
    image: caddy:alpine
    depends_on:
      - backend
    volumes:
      - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.snowtricks.rule: Host(`snowtricks.localhost`)
    ports:
      - 443:443

  backend:
    build:
      context: .
      dockerfile: system/backend/Dockerfile
      args:
        PHP_VERSION: 7.4
        COMPOSER_VERSION: 1
    volumes:
      - .:/app
      - ./system/backend/php-custom.ini:/usr/local/etc/php/php.ini

volumes:
  caddy_data:
  caddy_config:

#networks:
#  default:
#    external: true
#    name: proxy